---

# Production values
- set_fact: 
    arteria_siswrap_log: "{{ arteria_siswrap_log }}/production"
    runfolder_path: "{{ runfolder_path }}"
    arteria_siswrap_port: "{{ arteria_siswrap_port_prod }}"
  when: deployment_environment == "production"

# Staging values
- set_fact: 
    arteria_siswrap_log: "{{ arteria_siswrap_log }}/staging"
    runfolder_path: "{{ runfolder_path }}/staging/"
    arteria_siswrap_port: "{{ arteria_siswrap_port_stage }}"
  when: deployment_environment in [ "staging", "devel" ]

- include: install.yml
- include: sisyphus.yml

- name: ensure arteria-siswrap conf dir exists
  file:
    state: directory
    path: "{{ arteria_siswrap_config_root }}"
    mode: g+rwXs

- name: deploying arteria-siswrap app config
  template:
    src: siswrap_app.config.j2
    dest: "{{ arteria_siswrap_config_root }}/app.config"

- name: deploying arteria-siswrap logger config
  template:
    src: siswrap_logger.config.j2
    dest: "{{ arteria_siswrap_config_root }}/logger.config"

# TODO: Perl that launches needs to have the correct PERL5LIB setup. 
- name: modify uppsala's supervisord conf to start arteria-siswrap-ws 
  ini_file: 
    dest="{{ ngi_pipeline_conf }}/supervisord_upps.conf"
    section="program:arteria-siswrap-ws-{{ deployment_environment }}"
    option=command
    value="{{ arteria_siswrap_env_root }}/bin/siswrap-ws --configroot={{ arteria_siswrap_config_root }} --port={{ arteria_siswrap_port }}"
    backup=no
 
- name: modify uppsala's supervisord conf to autostart arteria-siswrap-ws
  ini_file: 
    dest="{{ ngi_pipeline_conf }}/supervisord_upps.conf"
    section="program:arteria-siswrap-ws-{{ deployment_environment }}"
    option=autorestart
    value=true
    backup=no

- name: add PERL5LIB to uppsala's sourceme script
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_upps_script }}"
              line="export PERL5LIB={{ ngi_resources }}/arteria/perl/lib/perl5/:$PERL5LIB"
              backup=no

