---

- name: install supervisord into NGI venv
  shell: conda install supervisor
  tags: func_accounts

- name: deploy crontab file for uppsala
  template: src="crontab_upps.j2" dest="{{ ngi_pipeline_conf }}/crontab_upps"
  tags: func_accounts

- name: deploy crontab file for stockholm
  template: src="crontab_sthlm.j2" dest="{{ ngi_pipeline_conf }}/crontab_sthlm"
  tags: func_accounts

- name: create ngi_resources folder 
  file: name={{ ngi_resources }} state=directory mode=g+s
  tags: func_accounts

- set_fact: 
    supervisord_log_dest: supervisord_log_dest_upps
    ngi_pipeline_web_port: ngi_pipeline_web_port_upps
  tags: func_accounts 

- name: deploy supervisord.conf for uppsala
  template: src="supervisord_site.conf.j2" dest="{{ ngi_pipeline_conf }}/supervisord_upps.conf"
  tags: func_accounts

- set_fact: 
    supervisord_log_dest: supervisord_log_dest_sthlm
    ngi_pipeline_web_port: ngi_pipeline_web_port_sthlm
  tags: func_accounts 

- name: deploy supervisord.conf for stockholm
  template: src="supervisord_site.conf.j2" dest="{{ ngi_pipeline_conf }}/supervisord_sthlm.conf"
  tags: func_accounts

- set_fact: 
    site: upps
  tags: func_accounts

- name: deploy start supervisord start script for uppsala
  template: src="start_supervisord_site.sh.j2" dest="{{ ngi_resources }}/start_supervisord_{{ site }}.sh"
  tags: func_accounts

- set_fact: 
    site: sthlm
  tags: func_accounts 

- name: deploy start supervisord start script for stockholm
  template: src="start_supervisord_site.sh.j2" dest="{{ ngi_resources }}/start_supervisord_{{ site }}.sh"
  tags: func_accounts

