---
taca_ngi_repo: https://github.com/SciLifeLab/taca-ngi-pipeline.git
taca_ngi_dest: "{{ sw_path }}/taca-ngi-pipeline"
taca_ngi_version: 422e5061c421256f465169a66dd4721f8e3cc710

statusdb_repo: "https://github.com/SciLifeLab/statusdb.git"
statusdb_dest: "{{ sw_path }}/statusdb"
statusdb_version: "ca2a3faea82a10359c70f7a7697db499b5c82b17"

flowcell_parser_repo: "https://github.com/SciLifeLab/flowcell_parser.git"
flowcell_parser_dest: "{{ sw_path }}/flowcell_parser"
flowcell_parser_version: "587cbfba9179f822a8e85946a13bfcd0b10b5a1b"

taca_repo: "https://github.com/SciLifeLab/TACA.git"
taca_dest: "{{ sw_path }}/TACA"
taca_version: 86f0d643ed7c9fccb38536c44f2c43feaf9a17b8
