---
- name: Fetch ngi_visualizations from GitHub
  git: repo="{{ ngi_visual_repo }}"
       dest="{{ ngi_visual_dest }}"
       version="{{ ngi_visual_version }}"
       force=yes

- name: Install ngi_visualizations requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ ngi_visual_dest }}/requirements.txt"

- name: Install ngi_visualizations
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ ngi_visual_dest }}"

- name: Copy Pandoc fix
  template: src=make_report.sh.j2 dest="{{ ngi_resources }}/make_report.sh" mode=0775

- name: Add Pandoc make_report function to common sourceme
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="source {{ ngi_resources }}/make_report.sh"
              backup=no

###START STOCKHOLM SPECIFIC

- name: Install couchDB (minimal version of statusDB)
  shell: "{{ ngi_pipeline_venv }}/bin/pip install couchdb"

- name: Copy statusDB credentials
  copy: src="files/{{ statusdb_creds }}" dest="{{ ngi_pipeline_conf }}/{{ statusdb_creds }}"

- name: Add statusDB envvar to sourceme 
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_sthlm_script }}
              line="export STATUS_DB_CONFIG={{ ngi_pipeline_conf }}/{{ statusdb_creds }}"
              backup=no

###END STOCKHOLM SPECIFIC
