multiqc_repo: https://github.com/ewels/MultiQC.git
multiqc_dest: "{{ root_path }}/sw/multiqc"
multiqc_version: "v0.7"

multiqc_ngi_repo: https://github.com/ewels/MultiQC_NGI.git
multiqc_ngi_dest: "{{ root_path }}/sw/multiqc_ngi"
multiqc_ngi_version: "v0.2.1"
