---

- name: ensure /etc/arteria/checksum dir exists
  file:
    state: directory
    path: "{{ arteria_checksum_config_root }}"

- name: deploy arteria-checksum app config
  template:
    src: checksum_app.config.j2
    dest: "{{ arteria_checksum_config_root }}/app.config"

- name: deploy arteria-checksum logger config
  template:
    src: checksum_logger.config.j2
    dest: "{{ arteria_checksum_config_root }}/logger.config"

