---

- name: Fetch statusdb from GitHub
  git: repo="{{ statusdb_repo }}"
       dest="{{ statusdb_dest }}"
       version="{{ statusdb_version }}"
       force=yes
  tags: taca

- name: Install statusDB requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ statusdb_dest }}/requirements.txt"
  tags: taca

- name: Install statusDB
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ statusdb_dest }}"
  tags: ngi_reports

- name: Fetch flowcell_parser from GitHub
  git: repo="{{ flowcell_parser_repo }}"
       dest="{{ flowcell_parser_dest }}"
       version="{{ flowcell_parser_version }}"
       force=yes
  tags: taca

- name: Install flowcell_parser requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ flowcell_parser_dest }}/requirements.txt"
  tags: taca

- name: Install flowcell_parser
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ flowcell_parser_dest }}"
  tags: taca

#COMMENT: HOPEFULLY NO LONGER A REQUIREMENT
#- name: Install cryptography python dependency
#  shell: "{{ ngi_pipeline_venv }}/bin/pip install cryptography"
#  tags: taca

- name: Fetch TACA from GitHub
  git: repo="{{ taca_repo }}"
       dest="{{ taca_dest }}"
       version="{{ taca_version }}"
       force=yes
  tags: taca

- name: Install TACA requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ taca_dest }}/requirements.txt"
  tags: taca

- name: Install TACA
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ taca_dest }}"
  tags: taca
