---
- name: Fetch non-SciLifeLab repos from GitHub
  git: repo="{{ item.repo }}"
       dest="{{ item.dest }}"
       version="{{ item.version }}"
  with_items:
  -  { repo: "{{ frc_align_repo }}", dest: "{{ frc_align_dest }}", version: "{{ frc_align_version }}" }

# Replaced by nougat singularity images
# Keeping for fallback purposes
#
#- name: Create FRC_Align build directory
#  file: path="{{ frc_align_dest }}/build" state=directory mode=g+rwxs
#
#- name: Make FRC_Align
#  shell: "module load boost && cmake .."
#  args: 
#    chdir: "{{ frc_align_dest }}/build"
#    creates: "{{ frc_align_dest }}/LICENSE"  
#
#- name: Fetch KmerGenie
#  get_url:
#    url: "{{ kmer_source }}/{{ kmer_version }}.tar.gz"
#    dest: "/scratch/{{ kmer_version }}.tar.gz"

#Added permission to make it easily removed.
- name: Unpack KmerGenie
  unarchive:
    src: "/scratch/{{ kmer_version }}.tar.gz"
    dest: "/scratch/"
    copy: no
    mode: 0755

- name: Create KmerGenie installation directory
  command: mv "/scratch/{{ kmer_version }}" "{{ kmer_dest }}"
  args:
    creates: "{{ kmer_dest }}"
    removes: "/scratch/{{ kmer_version }}"

- name: Install Kmergenie
  shell: "make"
  args:
    chdir: "{{ kmer_dest }}"

- name: Fix KmerGenie permission issue
  file:
    path: "{{ kmer_dest }}/kmergenie"
    state: touch
    mode: "u+rwx"

- name: Add KmerGenie to $PATH
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ kmer_dest }}:$PATH'
              backup=no

- name: Create NouGAT Singularity folder
  file: name="{{ ngi_resources }}/singularity/nougat" state=directory mode=g+s

- name: Download nougat singularity images
  command: singularity pull "{{ item }}"
  args:
    chdir: "{{ ngi_resources }}/singularity/nougat"
  with_items:
    - "{{ nougat_frc_source }}"
    - "{{ nougat_qa_source }}"

#Mode change to give scripts execute rights
- name: Create image-run scripts
  template: src="Singularity_runtime_script.j2" dest="{{ ngi_resources }}/singularity/nougat/{{ item.name }}" mode=0775
  with_items:
  - { name: "FRC" , image: "{{ nougat_frc_image }}" }
  - { name: "qaCompute", image: "{{ nougat_qa_image }}" }

- name: Copy Nougat paths configuration
  template: src="NouGAT_paths.conf.j2" dest="{{ ngi_pipeline_conf }}/NouGAT_paths.conf"

