---
- name: Create nextflow directory
  file: path="{{ nextflow_dest }}" state=directory mode=g+rwXs
  tags: ngi-rnaseq

- name: Download & install NextFlow 
  shell: "curl -fsSL get.nextflow.io | bash"
  args:
    chdir: "{{ nextflow_dest }}"
  tags: ngi-rnaseq

- name: Add nextflow to $PATH
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="export PATH={{ root_path }}/sw/nextflow:$PATH"
              backup=no
  tags: ngi-rnaseq

- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes
  tags: ngi-rnaseq

- name: Install NGI-RNAseq
  shell: "{{ ngi_pipeline_venv }}/bin/pip install . --upgrade"
  args:
    chdir: "{{ ngi_rnaseq_dest }}"
  tags: ngi-rnaseq

- name: Copy NGI-RNAseq config
  template: src="nextflow.config.j2" dest="{{ ngi_pipeline_conf }}/nextflow_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", proj: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", proj: "{{ ngi_pipeline_upps_delivery }}" }
  tags: ngi-rnaseq

- name: Set alias
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias nextflow='nextflow {{ ngi_rnaseq_dest }}/main.nf -c {{ ngi_pipeline_conf }}/nextflow_{{ item.site }}.config'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
  tags: ngi-rnaseq
