---

- name: deploy crontab file for uppsala
  template: src="crontab_upps.j2" dest="{{ ngi_pipeline_conf }}/crontab_upps"
  tags: funk_004

- name: create ngi_resources folder 
  file: name={{ ngi_resources }} state=directory
  tags: funk_004

- name: deploy supervisord.conf for uppsala
  template: src="supervisord_upps.conf.j2" dest="{{ ngi_pipeline_conf }}/supervisord_upps.conf"
  tags: funk_004

- name: deploy start supervisord start script for uppsala
  template: src="start_supervisord_upps.sh.j2" dest="{{ ngi_resources }}/start_supervisord_upps.sh"
  tags: funk_004

  
