---
- name: Fetch MultiQC from GitHub
  git: repo="{{ multiqc_repo }}"
       dest="{{ multiqc_dest }}"
       version="{{ multiqc_version }}"
       force=yes

#Remember to use --upgrade flag if using commit-id
- name: Install MultiQC
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ multiqc_dest }}"

- name: Fetch MultiQC NGI plugin from GitHub
  git: repo="{{ multiqc_ngi_repo }}"
       dest="{{ multiqc_ngi_dest }}"
       version="{{ multiqc_ngi_version }}"
       force=yes

#Remember to use --upgrade flag if using commit-id
- name: Install MultiQC NGI submodule
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ multiqc_ngi_dest }}"

- name: Add statusDB envvar to sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line="export STATUS_DB_CONFIG={{ ngi_pipeline_conf }}/{{ statusdb_creds }}"
              backup=no

- name: Deploy multiqc configs
  template: src="multiqc_config.yml.j2" dest="{{ ngi_pipeline_conf }}/multiqc_{{ item.site }}_config.yml"
  with_items: 
  - { site: "sthlm", disable_ngi_hooks: "False"}
  - { site: "upps", disable_ngi_hooks: "True"}

- name: Force multiqc to autorun config
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias multiqc='multiqc -c {{ ngi_pipeline_conf }}/multiqc_{{ item.site }}_config.yml'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
